import { Good } from '../good/good';

export const GOODS: Good[] = [
  { request_user: '', company: '理科研', product: 'STAR ニトリルグローブM', product_number: 'RSU-NGVM', quantity: '100枚入り', order_number: 1, note: ''},
  { request_user: '', company: '理科研', product: 'STAR ニトリルグローブL', product_number: 'RSU-NGVL', quantity: '100枚入り', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'ディスポカップ(ブロー成形)100ml', product_number: '1-4659-11', quantity: '1000個入', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'カウンティング・チェンバー用血球計算盤 カバーグラス　8000121', product_number: '2-5390-11', quantity: '10枚入', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'スタンダードシャーレ　φ60×15mm　60/15', product_number: '2-9169-03', quantity: '1個', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'シリコンチューブ　3×5', product_number: '6- 586-09', quantity: '2m', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'シリコンチューブ　5×7', product_number: '6- 586-16', quantity: '1m', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'シリコンチューブ　4×6', product_number: '6- 586-12', quantity: '2m', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'シリコンチューブ　6×8', product_number: '6- 586-20', quantity: '2m', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'シリコンチューブ　2×3', product_number: '6- 586-05', quantity: '1m', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'シリコンチューブ　2×4', product_number: '6- 586-07', quantity: '1m', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'シリコンチューブ　0.5×1', product_number: '6- 586-01', quantity: '4m', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'シリコンチューブ　0.5×1.5', product_number: '61-9432-27', quantity: '4m', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'シリコンチューブ　1.5×2.5', product_number: '6- 586-04', quantity: '2m', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'ビオラモマイクロチューブ 1.5ml', product_number: '1-1600-01', quantity: '1.5ml', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'ラボランスクリュー管瓶No.02 2mL', product_number: '9-852-01', quantity: '220本入', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'ラボランスクリュー管瓶No.01 3.5mL', product_number: '9-852-02', quantity: '110本入', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'ラボランスクリュー管瓶No.1 4mL', product_number: '9-852-03', quantity: '110本入', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'ラボランスクリュー管瓶No.2 6mL', product_number: '9-852-04', quantity: '110本入', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'ラボランスクリュー管瓶No.3 9mL', product_number: '9-852-05', quantity: '110本入', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'ラボランスクリュー管瓶No.4 13.5mL', product_number: '9-852-06', quantity: '55本入', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'ラボランスクリュー管瓶No.5 20mL', product_number: '9-852-07', quantity: '55本入', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'ラボランスクリュー管瓶No.6 30mL', product_number: '9-852-08', quantity: '55本入', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'ビオラモディスポピペット　ピーリング包装　25mL', product_number: '1-2247-05', quantity: '150本入', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'ラボランスクリュー管瓶No.7 50mL', product_number: '9-852-09', quantity: '55本入', order_number: 1, note: ''},
  { request_user: '', company: 'AXEL', product: 'バーナー専用ガスカートリッジ　CV360', product_number: '1-9881-11', quantity: '1本', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: 'pH試験紙　ロール　pH1-14', product_number: '1-1254-02', quantity: '1巻', order_number: 1, note: ''},
  { request_user: '', company: 'AXEL', product: 'チューブL型ジョイント L 12個入', product_number: '6-664-03', quantity: '12個入', order_number: 1, note: ''},
  { request_user: '', company: 'AXEL', product: 'チューブL型ジョイント LL 12個入', product_number: '6-664-04', quantity: '12個入', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: '薬包紙(パラピン)　小　90×90mm', product_number: '1-4560-01', quantity: '500枚入', order_number: 1, note: ''},
  { request_user: '', company: 'アズワン', product: '薬包紙(純白模造)　小　90×90mm', product_number: '1-4559-01', quantity: '1000枚入', order_number: 1, note: ''},
  { request_user: '', company: 'IWAKI', product: '無処理ディッシュ（浮遊細胞用） 100mm 300枚入', product_number: '1020-100', quantity: '300枚入', order_number: 1, note: ''},
  { request_user: '', company: 'Misumi', product: 'PFAマイクロチューブ 0.5×0.7 10m', product_number: '94-2109', quantity: '10m', order_number: 1, note: ''},
  { request_user: '', company: 'Misumi', product: 'クリーンノールディスポ静電指サックM千入', product_number: '1-4728-02', quantity: '千入', order_number: 1, note: ''},
  { request_user: '', company: '和光純薬', product: '和光一級-トルエン', product_number: '20101876', quantity: '500mL', order_number: 1, note: ''},
  { request_user: '', company: '和光純薬', product: '硫酸', product_number: '19214405', quantity: '500mL', order_number: 1, note: ''},
  { request_user: '', company: '和光純薬', product: 'くえん酸三ナトリウム', product_number: '203-13605', quantity: '500g', order_number: 1, note: ''},
  { request_user: '', company: '和光純薬', product: '試薬特級 2-プロパノール', product_number: '166-04836', quantity: '500mL', order_number: 1, note: ''},
  { request_user: '', company: '和光純薬', product: '塩酸', product_number: '080-01066', quantity: '500mL', order_number: 1, note: ''},
  { request_user: '', company: '和光純薬', product: 'ヨウ化ナトリウム', product_number: '198-02275', quantity: '500g', order_number: 1, note: ''},
  { request_user: '', company: '和光純薬', product: 'アセトン (超脱水)', product_number: '010-23463', quantity: '3L', order_number: 1, note: ''},
  { request_user: '', company: '和光純薬', product: '過酸化水素', product_number: '08104215', quantity: '500mL', order_number: 1, note: ''},
  { request_user: '', company: '和光純薬', product: 'グリセリン 3L', product_number: '07500611', quantity: '3L', order_number: 1, note: ''},
  { request_user: '', company: '和光純薬', product: '無水エタノール', product_number: '327-00027', quantity: '16L', order_number: 1, note: ''},
  { request_user: '', company: '和光純薬', product: 'Tween® 20, Molecular Biology Reagent', product_number: '591-18671', quantity: '50mL', order_number: 1, note: ''},
  { request_user: '', company: '和光純薬', product: 'ヘキサン', product_number: '082-06901', quantity: '100mL', order_number: 1, note: ''},
  { request_user: '', company: '和光純薬', product: '0.4w/v% トリパンブルー溶液', product_number: '207-17081', quantity: '100mL', order_number: 1, note: ''},
  { request_user: '', company: '和光純薬', product: 'アンモニア水', product_number: '016-03146', quantity: '500mL', order_number: 1, note: ''},
  { request_user: '', company: '和光純薬', product: 'スクロース', product_number: '196-00015', quantity: '500g', order_number: 1, note: ''},
  { request_user: '', company: '和光純薬', product: '安息香酸ナトリウム', product_number: '198-01295', quantity: '500g', order_number: 1, note: ''},
  { request_user: '', company: '和光純薬', product: 'ポリエチレングリコール 20,000', product_number: '168-11285', quantity: '500g', order_number: 1, note: ''},
  { request_user: '', company: '和光純薬', product: 'ポリエチレングリコール 6000 1', product_number: '169-09125', quantity: '500g', order_number: 1, note: ''},
  { request_user: '', company: '関東化学', product: '1mol/L 水酸化ナトリウム溶液(1N)', product_number: '37847-08', quantity: '500mL', order_number: 1, note: ''},
  { request_user: '', company: '松浪硝子工業株式会社 ', product: '松浪スライドグラス S9112 50入', product_number: '83-0306', quantity: '50枚入', order_number: 1, note: ''},
  { request_user: '', company: '松浪硝子工業株式会社 ', product: '松浪スライドグラス S1111 100入', product_number: '83-0276', quantity: '100枚入', order_number: 1, note: ''},
  { request_user: '', company: '松浪硝子工業株式会社 ', product: 'NEOカバーグラス 24×36 200入', product_number: 'C024361', quantity: '200枚入', order_number: 1, note: ''},
  { request_user: '', company: '松浪硝子工業株式会社 ', product: 'NEOカバーグラス 24×45 200入', product_number: 'C024451', quantity: '200枚入', order_number: 1, note: ''},
  { request_user: '', company: '松浪硝子工業株式会社 ', product: 'マイクロスライドグラス(白縁磨 No.1)', product_number: 'S1111', quantity: '100枚入', order_number: 1, note: ''},
  { request_user: '', company: 'テルモ', product: 'テルモシリンジ SS-10SZ2138P', product_number: '1-2046-01', quantity: '100本入', order_number: 1, note: ''},
  { request_user: '', company: 'テルモ', product: 'テルモシリンジ注射針付 2.5mL 21G 5/8" 緑　SS-02LZ2116V', product_number: '61-9704-30', quantity: '100本入', order_number: 1, note: ''},
  { request_user: '', company: 'テルモ', product: 'テルモシリンジ(R)注射針付 1mL ツベルクリン用 26G 茶　SS-01T2613S', product_number: '1-1793-02', quantity: '100本入', order_number: 1, note: ''},
  { request_user: '', company: 'テルモ', product: '注射針 オレンジ 100本入り 25G NN-2525R', product_number: '61-9703-87', quantity: '100本入', order_number: 1, note: ''},
  { request_user: '', company: 'テルモ', product: 'テルモ　ディスポシリンジ', product_number: '72-0165', quantity: '1本', order_number: 1, note: ''},
  { request_user: '', company: 'タカラバイオ株式会社', product: 'CELLBANKER® 1 ', product_number: 'CB011', quantity: '100mL', order_number: 1, note: ''},
  { request_user: '', company: 'メルク', product: 'ポリ(ジアリルジメチルアンモニウムクロリド)溶液', product_number: '409014-1L', quantity: '1L', order_number: 1, note: ''},
  { request_user: '', company: 'サンプラテック', product: 'エコノマイクロチューブ ', product_number: '27131', quantity: '1.5mL 500本入 2箱', order_number: 1, note: ''},
  { request_user: '', company: 'ナカライテスク', product: 'MEM培地 (アール塩, L-グルタミン含有)(液体)', product_number: '21442-25', quantity: '500mL', order_number: 1, note: ''},
  { request_user: '', company: '東京化成工業株式会社', product: 'N-Isopropylacrylamide (stabilized with MEHQ)', product_number: 'I0401', quantity: '25g', order_number: 1, note: ''},
  { request_user: '', company: '東京化成工業株式会社', product: '3-アミノプロピルトリエトキシシラン EP', product_number: 'A0439', quantity: '25g', order_number: 1, note: ''},
  { request_user: '', company: '東京化成工業株式会社', product: '1-(3-ジメチルアミノプロピル)-3-エチルカルボジイミド塩酸塩', product_number: 'D1601', quantity: '25g', order_number: 1, note: ''},
  { request_user: '', company: 'ケニス', product: '滅菌シャーレ　DM-20 深型　100枚 ', product_number: '1-132-0040', quantity: '100枚入', order_number: 1, note: ''},
  { request_user: '', company: 'ケニス', product: '滅菌シャーレ 90φ×19mm　100枚 ', product_number: '1-132-157', quantity: '100枚入', order_number: 1, note: ''},
  { request_user: '', company: 'Clontech', product: 'Trypsin / EDTA (0.04 % / 0.03 %)', product_number: 'D13084', quantity: '100枚入', order_number: 1, note: ''},
  { request_user: '', company: '信越シリコーン', product: 'KE-106 1Kg', product_number: 'KE-106', quantity: '1Kg', order_number: 1, note: ''},
  { request_user: '', company: '信越シリコーン', product: 'CAT-RG 100g', product_number: 'CAT-RG', quantity: '100g', order_number: 1, note: ''},
  { request_user: '', company: 'Eppendorf', product: 'epT.I.P.S.® Standard, Eppendorf Quality™, 2 – 200 µL, 53 mm, イエロー, 黄色チップ', product_number: '0030000870', quantity: '2 袋 × 500 本', order_number: 1, note: ''},
  { request_user: '', company: 'Eppendorf', product: 'epT.I.P.S.® Standard, Eppendorf Quality™, 20 – 300 µL, 55 mm, オレンジ, 黄色チップ', product_number: '0030000897', quantity: '2 袋 × 500 本', order_number: 1, note: ''},
  { request_user: '', company: 'Eppendorf', product: 'epT.I.P.S.® Standard, Eppendorf Quality™, 50 – 1,000 µL, 71 mm, ブルー, 青チップ', product_number: '0030000919', quantity: '2 袋 × 500 本', order_number: 1, note: ''},
  { request_user: '', company: 'Eppendorf', product: 'epT.I.P.S.® Standard, Eppendorf Quality™, 0.25 – 2.5 mL, 115 mm, 赤色, カラーレス', product_number: '0030000951', quantity: '5 袋 × 100 本', order_number: 1, note: ''},
  { request_user: '', company: 'Eppendorf', product: 'epT.I.P.S.® Standard, Eppendorf Quality™, 50 – 1,250 µL, 76 mm, 緑色, カラーレス', product_number: '0030000935', quantity: '4 袋 × 250 本', order_number: 1, note: ''},
  { request_user: '', company: 'Eppendorf', product: 'epT.I.P.S.® Standard, Eppendorf Quality™, 0.5 – 20 µL L, 46 mm, ライトグレー, カラーレス', product_number: '0030000854', quantity: '2 袋 × 500 本', order_number: 1, note: ''},
  { request_user: '', company: '三商', product: 'カルシウム菅 φ12×120', product_number: '82-2470-4', quantity: '1本', order_number: 1, note: ''},
  { request_user: '', company: '三商', product: 'カルシウム菅 φ12×150', product_number: '82-2471-4 ', quantity: '1本', order_number: 1, note: ''},
  { request_user: '', company: '三商', product: 'PFAチューブ 4×3', product_number: '94-2069', quantity: '1m', order_number: 1, note: ''},
  { request_user: '', company: '三商', product: 'PFAチューブ 0.5×0.7', product_number: '94-2109', quantity: '10m', order_number: 1, note: ''},
  { request_user: '', company: '三商', product: 'ＰＰチューブコネクター Ｓ－１', product_number: '93-1875', quantity: '１０個入', order_number: 1, note: ''},
  { request_user: '', company: 'ナカライテスク', product: 'テトラクロロ金(Ⅲ)酸四水和物', product_number: '17302-01', quantity: '1g', order_number: 1, note: ''},
  { request_user: '', company: '信越化学', product: 'シリコーンオイル50CS 1kg', product_number: 'KF-96-50cs', quantity: '1kg', order_number: 1, note: ''},
  { request_user: '', company: 'COREFRONT', product: '蛍光粒子 10µm 10ml', product_number: 'G1000', quantity: '10ml', order_number: 1, note: ''},
  { request_user: '', company: 'COREFRONT', product: 'G25 15ml 蛍光粒子 グリーン', product_number: 'G25', quantity: '15ml', order_number: 1, note: ''},
  { request_user: '', company: '健栄製薬株式会社', product: '無水エタノール', product_number: '4987286407616', quantity: '500mL', order_number: 1, note: ''},
  { request_user: '', company: 'ジオマテック', product: 'ITO膜付きガラス', product_number: '1007', quantity: '5枚入', order_number: 1, note: ''},
  { request_user: '', company: '寺岡製作所', product: 'カプトンⓇ粘着テープ', product_number: '650R #12', quantity: '20m', order_number: 1, note: ''},
];
